### ISSUE TITLE
translate property with relative percentage do not work

### ISSUE THREAD

**Issue by shirohana** [juliangarnier/anime#214]
Hello,

As title, here's my code:

```javascript
anime({
  targets: el,
  translateX: '-=100%'  // <- It became to '-100px' in fact
})
```

Is it a bug or expected behavior?

**Comment by juliangarnier** [comment]
Thanks for pointing this.
Fixed in next release!

**Comment by syropian** [comment]
This doesn't seem to be working for me in the latest version. If I have an element with like so:
```css
.my-el {
  transform: translateY(20%);
}
```

and do something like
```js
anime({
  targets: ".my-el",
  translateY: "-=5%"
})
```

i expect it to have a `translateY` of `15%`, but instead it sets it to `translateY(-5%)`

**Comment by trych** [comment]
I have the same problem.

```js
.my-el {
  transform: translateX(-40%);
}
```

```js
anime({
  targets: ".my-el",
  translateX: "-=60%"
})
```

Target starts animating at `translateX(0)` and translates to `translate(-60%)` instead of going from `translate(-40%)` to `translate(-100%)` as expected. Is this something that broke in recent releases?

**Comment by aderchox** [comment]
It's not working for me either. Here's a (an ugly) workaround I'll share for future readers until this gets fixed (hopefully).

Just specify which values are going to be animated (e.g., the translateX value) and then just add its initial value as a variable on the root element, then get and set it with your anime.js just as you could target any other JavaScript variables (i.e.: [link](https://animejs.com/documentation/#JSobject)). I tried this and it works.

**Comment by stephen-97** [comment]
Still not working for me too. @trych 
Thank you for the tip @aderchox
