### ISSUE TITLE
anime is not defined

### ISSUE THREAD

**Issue by e30alex** [juliangarnier/anime#489]
I'm getting **Uncaught ReferenceError: anime is not defined** when i try to call the anime function.
I'm using webpack and npm.

import anime from 'animejs/lib/anime.es.js';

I'm mentioning that all other libraries are working fine, except this one.

Can you give me a solution?

Thanks!

**Comment by juliangarnier** [comment]
You are probably not including the correct file for your environment.
`'lib/anime.es.js'` is for ES6 modules import syntax.
`'lib/anime.js'` is the CommonJS import syntax (@e30alex it's probably the one you should use).
`'lib/anime.min.js'` is the classic, ES5 minified version (@arun99178 it's probably the one you should use).

**Comment by tr1s** [comment]
@juliangarnier same issue.

I'm using webpack and when I call anime() in a script outside of the index.js (which is being imported) I get an undefined error. But when I call anime() in the index.js is works. Do you know why this might happen?

I'm using my [webpack boilerplate](https://github.com/tr1s/tris-webpack-boilerplate). Any help/understanding would be greatly appreciated.

**Comment by Pixney-William** [comment]
Same issue here. Neither of these works:

```
import anime from 'lib/anime.es.js';
import anime from 'anime.es.js';
```

**Comment by mittelgrau** [comment]
> Same issue here. Neither of these works:
> 
> ```
> import anime from 'lib/anime.es.js';
> import anime from 'anime.es.js';
> ```

for me  ```import anime from 'animejs/lib/anime.es.js' ``` worked

**Comment by tr1s** [comment]
Again, my issue is it works if I'm calling anime() in the same file as the import, but does not work if I'm calling anime inside an import. For example:

This does not work. Anime is called inside of the `import './scripts/script.js';` (very last import).
<img width="551" alt="CleanShot 2019-03-27 at 11 10 21@2x" src="https://user-images.githubusercontent.com/19172250/55087751-f5b7a500-5080-11e9-996d-20ed4224602e.png">

But this does work.
<img width="559" alt="CleanShot 2019-03-27 at 11 13 02@2x" src="https://user-images.githubusercontent.com/19172250/55087975-51822e00-5081-11e9-97ce-7d336d11c2f1.png">

Why would this be @juliangarnier, @mittelgrau? My vanilla-tilt call is inside my script, I have no other issues with any other libraries. Just anime doesn't want to work inside an import. What's different about anime.js that it doesn't work like the rest with Webpack?

@e30alex, @Pixney-William, did you ever find solutions?

**Comment by royJackman** [comment]
If this is still relevant:
I had this issue and it was fixed using
`import { default as anime } from '../node_modules/animejs/lib/anime.es.js';`

**Comment by CheapSmokes** [comment]
Thanks @royJackman. This trick works a treat when using AnimeJS across multiple files from a single import.

**Comment by Anastasia-Nayita** [comment]
If it's relevant to someone,
this line worked for me 
`<script src="https://cdn.jsdelivr.net/npm/animejs@3.0.1/lib/anime.min.js"></script>`

**Comment by greyswrld** [comment]
still having the same error but in my case i want to add the staggering effect anytime i type delay: anime.stagger(100), it throws and error of anime is not defined

**Comment by princeborn1999** [comment]
thanks to save my day~ I change 'anime.min.js' to 'anime.js', then it works.

**Comment by golam71** [comment]
make a script tag 

<script>
import anime from "animejs"
</script>



that wont work
no one exports named export called default
either do import anime from 'asd';
then it will use the default import
import {anime} from 'avc';
this uses named export

**Comment by RejhyT** [comment]
> If this is still relevant: I had this issue and it was fixed using `import { default as anime } from '../node_modules/animejs/lib/anime.es.js';`

I used this in my script code and  it's work ..
`import anime from '/node_modules/animejs/lib/anime.es.js';`
Also i must set script to 'type="module"'
`<script defer type="module"  src="/js/main.js"></script>`

**Comment by Gorbulev-Sergey** [comment]
Hi guys! It worked like this for me with ts:
1) added a file .d.ts file with:
`declare module '/node_modules/animejs/lib/anime.es.js';`
2) in my script file added:
`import anime from 'animejs';`
